/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TampilkanWebcam.java
 *
 * Created on Nov 21, 2011, 9:14:00 AM
 */
package belajar;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoDataSourceException;
import javax.media.Player;
import javax.media.protocol.DataSource;
import javax.swing.JOptionPane;

/**
 *
 * @author endy
 */
public class TampilkanWebcam extends javax.swing.JFrame {

    /** Creates new form TampilkanWebcam */
    public TampilkanWebcam() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCapture = new javax.swing.JButton();
        txtWebcam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

        btnCapture.setText("Start Capture");
        btnCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaptureActionPerformed(evt);
            }
        });

        jLabel1.setText("Webcam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(txtWebcam, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCapture)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapture)
                    .addComponent(jLabel1)
                    .addComponent(txtWebcam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaptureActionPerformed
        try {
            MediaLocator webcam = new MediaLocator(txtWebcam.getText());
            System.out.println("Membuat media locator "+txtWebcam.getText());
            DataSource ds = Manager.createDataSource(webcam);
            System.out.println("Membuat datasource");
            Player p = Manager.createRealizedPlayer(ds);
            System.out.println("Player siap");
            Component screen = p.getVisualComponent();
            if(screen == null){
                JOptionPane.showMessageDialog(this, "Visual Component tidak ada", 
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            this.getContentPane().add(screen, BorderLayout.CENTER);
            this.getContentPane().add(p.getControlPanelComponent(), BorderLayout.SOUTH);
            p.start();
            
            // refresh frame
            this.setVisible(false);
            this.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TampilkanWebcam.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnCaptureActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TampilkanWebcam().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapture;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtWebcam;
    // End of variables declaration//GEN-END:variables
}
